"""add punti to passenger

Revision ID: 3744d17be140
Revises: d3da32342446
Create Date: 2026-01-15 13:48:43.943637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3744d17be140'
down_revision = 'd3da32342446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punti', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.drop_column('punti')

    # ### end Alembic commands ###
