"""empty message

Revision ID: 7f97dad7cd72
Revises: 3744d17be140
Create Date: 2026-01-21 13:41:09.061790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f97dad7cd72'
down_revision = '3744d17be140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punti', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('punti')

    # ### end Alembic commands ###
