"""Inizio

Revision ID: d3da32342446
Revises: 
Create Date: 2026-01-05 16:26:27.872288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3da32342446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cognome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('eta', sa.Integer(), nullable=False),
    sa.Column('CF', sa.String(length=50), nullable=False),
    sa.Column('NrPatente', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CF'),
    sa.UniqueConstraint('NrPatente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cognome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('eta', sa.Integer(), nullable=False),
    sa.Column('CF', sa.String(length=50), nullable=False),
    sa.Column('prelievo', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CF'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeScuola', sa.String(length=100), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=False),
    sa.Column('suffix', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    op.drop_table('passengers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
